# -*- coding: utf-8 -*-
"""telebot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LUiBvJtKNZxNdDbhLg3l4yH7kLGl0f7y

# Иморт библиотек
"""

pip install pyTelegramBotAPI

from PIL import Image

!apt update

import telebot

from telebot import types

from google.colab import drive
drive.mount('/content/drive')

!pip3 install pillow

import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/bot/')

import style_transfer_class

"""# Бот"""

TOKEN = ""
tel_bot = telebot.TeleBot(TOKEN)

n = 0
zap = False
@tel_bot.message_handler(content_types=['text'])
def start(message):
    if message.text == '/start':
        tel_bot.send_message(message.from_user.id, "Привет! Это бот, которому можно отправить две фотографии и получить в ответ фото с перенесенным стилем. Пришлите, пожалуйста, изображение, с которого нужно перенести стиль")
        tel_bot.register_next_step_handler(message, get_style_image)
    else:
        tel_bot.send_message(message.from_user.id, 'Напиши /start')
 
def get_style_image(message): #
    global style_image
    global src_style
    if message.content_type!= 'photo':
        tel_bot.send_message(message.chat.id, 'Мне нужно изображение, отправьте, пожалуйста')
        tel_bot.register_next_step_handler(message, get_style_image)
    if message.content_type== 'photo': 
        

        #пытаемся фото сохранить 
        file_info = tel_bot.get_file(message.photo[len(message.photo)-1].file_id)
        style_image = tel_bot.download_file(file_info.file_path)

        src_style='/content/drive/My Drive/Colab Notebooks/bot/'+file_info.file_path
        #src='/content/drive/My Drive/Colab Notebooks/bot/image/style_image.jpg'
        with open(src_style, 'wb') as new_file:
           new_file.write(style_image)
         #пытаемся фото сохранить 
        

        tel_bot.send_message(message.from_user.id, 'Спасибо, теперь мне нужно изображение, на которое нужно перенести стиль') 
        tel_bot.register_next_step_handler(message, get_content_image)
 
def get_content_image(message):
    global content_image
    global src_content
    global output
    if message.content_type!= 'photo':
        tel_bot.send_message(message.chat.id, 'Мне нужно изображение, отправьте, пожалуйста')
    if message.content_type== 'photo':     
       
        #пытаемся фото сохранить 
        file_info = tel_bot.get_file(message.photo[len(message.photo)-1].file_id)
        content_image = tel_bot.download_file(file_info.file_path)

        src_content='/content/drive/My Drive/Colab Notebooks/bot/'+file_info.file_path
        #src='/content/drive/My Drive/Colab Notebooks/bot/image/content_image.jpg'
        with open(src_content, 'wb') as new_file:
           new_file.write(content_image)
         #пытаемся фото сохранить 
        

        tel_bot.send_message(message.chat.id,'Спасибо, начинаю обработку')
        object_style_transfer = alex_style_transfer_class.py.StyleTransfer(style_image_path=src_style,
                                                    content_image_path=src_content) 
        output =object_style_transfer.transfer_style(out_image_path= "/content/drive/My Drive/Colab Notebooks/bot/image/out_image.png") 
        photo = open('/content/drive/My Drive/Colab Notebooks/bot/image/out_image.png', 'rb')
        tel_bot.send_photo(message.from_user.id, photo)
       
#tel_bot.send_photo(message.chat.id, style_image) отправка фото

tel_bot.polling()